### PR TITLE
Fixed ListDict for 3.5+ by using python collections over c collections

### LINKED ISSUE #67: Menu.insert_before does not work in Python 3.5+
```
  File "/usr/local/lib/python3.6/site-packages/rumps/rumps.py", line 434, in insert_before
    super(Menu, self).insert_before(existing_key, (key, menuitem))
  File "/usr/local/lib/python3.6/site-packages/rumps/utils.py", line 30, in insert_before
    self.__insertion(self._OrderedDict__map[existing_key][0], key_value)
AttributeError: 'Menu' object has no attribute '_OrderedDict__map'
```

### PR DESCRIPTION
**Pull request by mitchmcdee**
fixes #67

### CODE REVIEW

**Comment by jaredks** [comment]
Error in Python 2.7,

```
Traceback (most recent call last):
  File "rumps/rumps/rumps.py", line 974, in callback_
    return _call_as_function_or_method(callback, self)
  File "rumps/rumps/rumps.py", line 322, in _call_as_function_or_method
    return func(event)
  File "test.py", line 59, in test_callback
    app.menu.insert_before('Preferences', 'testing')
  File "rumps/rumps/rumps.py", line 441, in insert_before
    super(Menu, self).insert_before(existing_key, (key, menuitem))
  File "rumps/rumps/utils.py", line 34, in insert_before
    self.__insertion(self._OrderedDict__map[existing_key].prev, key_value)
AttributeError: 'list' object has no attribute 'prev'
```

Closing in favor of https://github.com/jaredks/rumps/pull/93
