### ISSUE TITLE
Menu.insert_before does not work in Python 3.5+

### ISSUE THREAD

**Issue by cbenhagen** [jaredks/rumps#67]
```
  File "/usr/local/lib/python3.6/site-packages/rumps/rumps.py", line 434, in insert_before
    super(Menu, self).insert_before(existing_key, (key, menuitem))
  File "/usr/local/lib/python3.6/site-packages/rumps/utils.py", line 30, in insert_before
    self.__insertion(self._OrderedDict__map[existing_key][0], key_value)
AttributeError: 'Menu' object has no attribute '_OrderedDict__map'
```

**Comment by jpulgarin** [comment]
`insert_after` also doesn't work for the same reason.

**Comment by mitchmcdee** [comment]
Yeah I had this issues and fixed it by forcing ListDict to use the python version of `collections` (the C version does not expose the underlying map in Python 3.5+).

I was going to put up a PR, but Jared hasn't responded to my other PR even after multiple attempts of contact, so I assume this project is dead :\

**Comment by cbenhagen** [comment]
Please make a PR anyway. Others could want to use it in their own forks until it got merged here. 

Let's open a constructive discussion about the future of this project instead of declaring it dead. Maybe we could help @jaredks maintaining it?

**Comment by mitchmcdee** [comment]
Good idea on both fronts, will put up a PR sometime after my exams :^)
